CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE BRANCH(
	BRANCH_NO INT PRIMARY KEY,
    MANAGER_ID INT,
    B_ADDRESS VARCHAR(25)
);

CREATE TABLE BOOKS(
	ISBN INT PRIMARY KEY,
    GENRE VARCHAR(25),
    TITLE VARCHAR(25), 
    PUBLISHER VARCHAR(25),
    PRICE INT,
    AUTHOR VARCHAR(25),
    STAT VARCHAR(25),
    BRANCH_NO INT,
    FOREIGN KEY (BRANCH_NO) REFERENCES BRANCH(BRANCH_NO)
);

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    SALARY INT,
    DES VARCHAR(25),
    EMP_NAME VARCHAR(25),
    BRANCH_NO INT,
    FOREIGN KEY (BRANCH_NO) REFERENCES BRANCH(BRANCH_NO)
);

CREATE TABLE CUSTOMER(
	CUSTOMER_ID INT PRIMARY KEY,
    BOOKS_ISSUED INT, 
    CUSTOMER_NAME VARCHAR(25),
    CUS_ADDRESS VARCHAR(25),
    BRANCH_NO INT
);

CREATE TABLE ISSUECARD(
	ISSUE_ID INT PRIMARY KEY,
    ISSUE_DATE DATE, 
    ISBN INT,
    ISSUE_BOOK_NAME VARCHAR(25),
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE RETURNCARD(
	RETURN_ID INT PRIMARY KEY, 
    RETURN_DATE DATE,
    ISBN INT,
    RETURN_BOOK_NAME VARCHAR(25),
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);



